[package]
name = "invariant"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
traceable_result.workspace = true
math.workspace = true
decimal.workspace = true
io.workspace = true
contracts.workspace = true
gear-core.workspace = true
fungible-token-io.workspace = true
fungible-token-state.workspace = true

[build-dependencies]
gear-wasm-builder.workspace = true
gmeta.workspace = true
io.workspace = true
state.workspace = true

[dev-dependencies]
gtest.workspace = true
gclient.workspace = true
tokio.workspace = true
fungible-token.workspace = true
fungible-token-io.workspace = true
fungible-token-state.workspace = true

[features]
binary-vendor = []
wasm-opt = ["gear-wasm-builder/wasm-opt"]
default = ["binary-vendor", "wasm-opt"]

[workspace]
members = ["state", "xtask"]

[workspace.dependencies]
# Library dependencies
decimal.path = "calc/decimal"
math.path = "calc/math"
traceable_result.path = "calc/traceable_result"
contracts.path = "src/contracts"

# Local contracts
fungible-token.path = "fungible-token"

# Contract dependencies
state.path = "state"
io.path = "io"
fungible-token-io.path = "fungible-token/io"
fungible-token-state.path = "fungible-token/state"

# Gear dependencies
gstd = "1.1.1"
gear-wasm-builder = "1.1.1"
gmeta = "1.1.1"
gear-core = "1.1.1"
gtest = { git = "https://github.com/gear-tech/gear.git", tag = "v1.1.1" }
gclient = { git = "https://github.com/gear-tech/gear.git", tag = "v1.1.1" }

# External
tokio = { version = "1", features = ["full"] }
xshell = "0.2"
anyhow = "1"