[package]
name = "invariant"
version.workspace = true
edition.workspace = true

[dependencies]
gstd.workspace = true
traceable_result.workspace = true
math.workspace = true
decimal.workspace = true
io.workspace = true
contracts.workspace = true
gear-core.workspace = true
futures = { version = "0.3.30", features = ["async-await"], default-features = false }

[build-dependencies]
gear-wasm-builder.workspace = true
gmeta.workspace = true
io.workspace = true
state.workspace = true

[dev-dependencies]
gtest.workspace = true
gclient.workspace = true
tokio.workspace = true
gstd = {workspace=true, features=["debug"]}

[features]
binary-vendor = []
wasm-opt = ["gear-wasm-builder/wasm-opt"]
default = ["binary-vendor", "wasm-opt"]
test = ["gstd/debug"]

[workspace]
members = ["state", "xtask", "gear-erc20/app", "gear-erc20/wasm" ]
package.version = "0.1.0"
package.edition = "2021"

[workspace.dependencies]
# Library dependencies
decimal.path = "calc/decimal"
math.path = "calc/math"
traceable_result.path = "calc/traceable_result"
contracts.path = "src/contracts"

# Local contracts
gear-erc20.path = "gear-erc20/app"
gear-erc20-wasm.path = "gear-erc20/wasm"

# Contract dependencies
state.path = "state"
io.path = "io"

# Gear dependencies
gstd = "1.4.1"
gear-wasm-builder = "1.4.1"
gmeta = "1.4.1"
gear-core = { git = "https://github.com/gear-tech/gear.git", tag = "v1.4.1" }
gtest = { git = "https://github.com/gear-tech/gear.git", tag = "v1.4.1" }
gclient = { git = "https://github.com/gear-tech/gear.git", tag = "v1.4.1" }
sails-idl-gen = { git = "https://github.com/gear-tech/sails", rev = "51b731ef8f064a23c6c98fa92d06eeafe44d3f9d" }
sails-rtl = { git = "https://github.com/gear-tech/sails", rev = "51b731ef8f064a23c6c98fa92d06eeafe44d3f9d" }

# External
tokio = { version = "1.36", features = ["full"] }
xshell = "0.2"
anyhow = "1"

log = "*"
env_logger = "*"
primitive-types = { version = "*", default-features = false }
