[package]
name = "invariant"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd = "1.1.0"
decimal = { path = "src/decimal" }
traceable_result = { path = "src/traceable_result" }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = [
  "derive",
] }
scale-info = { version = "2.6", default-features = false, features = [
  "derive",
], optional = true }
io = { path = "./io" }

[build-dependencies]
gear-wasm-builder = "1.1.0"
gmeta = "1.1.0"
io = { path = "./io" }

[dev-dependencies]
gtest = "1.1.0"

[features]
binary-vendor = []
wasm-opt = ["gear-wasm-builder/wasm-opt"]
default = ["binary-vendor", "wasm-opt"]
