[package]
name = "invariant"
version.workspace = true
edition.workspace = true

[dependencies]
gcore.workspace = true
gear-core.workspace = true
gstd.workspace = true
traceable_result.workspace = true
math.workspace = true
decimal.workspace = true
io.workspace = true
contracts.workspace = true
sails-rtl.workspace = true
futures = { version = "0.3.30", features = [
  "async-await",
], default-features = false }

[build-dependencies]
gcore.workspace = true
gear-core.workspace = true
gstd.workspace = true
gear-wasm-builder.workspace = true
gmeta.workspace = true
io.workspace = true
sails-idl-gen.workspace = true

[dev-dependencies]
gtest.workspace = true
gclient.workspace = true
tokio.workspace = true
gstd = { workspace = true, features = ["debug"] }

[features]
binary-vendor = []
wasm-opt = ["gear-wasm-builder/wasm-opt"]
default = ["binary-vendor", "wasm-opt"]
test = ["gstd/debug"]

[workspace]
members = ["xtask", "gear-erc20/wasm", "src/wasm"]
package.version = "0.1.0"
package.edition = "2021"

[workspace.dependencies]
# Library dependencies
decimal.path = "calc/decimal"
math.path = "calc/math"
traceable_result.path = "calc/traceable_result"
contracts.path = "src/contracts"

# Local contracts
gear-erc20.path = "gear-erc20/app"
invariant.path = "."
# Contract dependencies
io.path = "io"

# Gear dependencies
gstd.version = "=1.4.1"
gtest.version = "=1.4.1"
gear-core.version = "=1.4.1"
gcore.version = "=1.4.1"
gsys.version = "=1.4.1"
gear-wasm-builder.version = "=1.4.1"
gwasm-builder = {version = "=1.4.1", package = "gear-wasm-builder"}
gmeta.version = "=1.4.1"
gclient.version = "=1.4.1"
gear-core-errors.version = "=1.4.1"
sails-idl-gen = { git = "https://github.com/gear-tech/sails", rev = "31a3c1a06817b69040af0c069967dd0b31c9530b" }
sails-rtl = { git = "https://github.com/gear-tech/sails", rev = "31a3c1a06817b69040af0c069967dd0b31c9530b" }

# External
tokio = { version = "1.36", features = ["full"] }
xshell = "0.2"
anyhow = "1"
log = "*"
env_logger = "*"
primitive-types = { version = "*", default-features = false }

