[package]
name = "state"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
gmeta = { workspace = true, features = ["codegen"] }
io.workspace = true
contracts.workspace = true

[build-dependencies]
gear-wasm-builder = { workspace = true, features = ["metawasm"] }