[package]
name = "math"
version = "0.1.0"
edition = "2021"

[dependencies]
decimal.workspace = true
traceable_result.workspace = true
gstd.workspace = true
sails-rs.workspace = true
uint = { version = "0.9", default-features = false }

[lib]
path = "lib.rs"