[package]
name = "contracts"
version = "0.1.0"
edition = "2021"

[dependencies]
gstd.workspace = true
math.workspace = true
traceable_result.workspace = true
decimal.workspace = true
sails-rs.workspace = true

[lib]
path = "lib.rs"